openapi: 3.0.0
info:
  title: Random Joke API
  description: API for retrieving a random joke
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
paths:
  /random-joke:
    get:
      summary: Get a random joke
      responses:
        '200':
          description: A random joke object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RandomJoke'
components:
  schemas:
    RandomJoke:
      type: object
      properties:
        id:
          type: integer
          description: The unique ID of the joke.
        joke:
          type: string
          description: The random joke text.
