logging:
  level:
    org.springframework: INFO
spring:
  cloud:
    compatibility-verifier:
      enabled: false

springdoc:
  api-docs:
    path: /apispecs/api-specs.yaml
  swagger-ui:
    path: /api/swagger-ui.html

jokeapi:
  url: https://v2.jokeapi.dev